export const GET_ADMIN_DASHBOARD_DATA_REQUEST =
  "GET_ADMIN_DASHBOARD_DATA_REQUEST";
export const GET_ADMIN_DASHBOARD_DATA_SUCCESS =
  "GET_ADMIN_DASHBOARD_DATA_SUCCESS";
export const GET_ADMIN_DASHBOARD_DATA_FAIL = "GET_ADMIN_DASHBOARD_DATA_FAIL";

export const GET_ALL_HELP_MESSAGES_REQUEST = "GET_ALL_HELP_MESSAGES_REQUEST";
export const GET_ALL_HELP_MESSAGES_SUCCESS = "GET_ALL_HELP_MESSAGES_SUCCESS";
export const GET_ALL_HELP_MESSAGES_FAIL = "GET_ALL_HELP_MESSAGES_FAIL";
