export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";

export const GET_ALL_BANNER_REQUEST = "GET_ALL_BANNER_REQUEST";
export const GET_ALL_BANNER_SUCCESS = "GET_ALL_BANNER_SUCCESS";
export const GET_ALL_BANNER_FAIL = "GET_ALL_BANNER_FAIL";

export const UPDATE_BANNER_IMAGE_REQUEST = "UPDATE_BANNER_IMAGE_REQUEST";
export const UPDATE_BANNER_IMAGE_SUCCESS = "UPDATE_BANNER_IMAGE_SUCCESS";
export const UPDATE_BANNER_IMAGE_FAIL = "UPDATE_BANNER_IMAGE_FAIL";

export const UPDATE_BANNER_STATUS_REQUEST = "UPDATE_BANNER_STATUS_REQUEST";
export const UPDATE_BANNER_STATUS_SUCCESS = "UPDATE_BANNER_STATUS_SUCCESS";
export const UPDATE_BANNER_STATUS_FAIL = "UPDATE_BANNER_STATUS_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";
