export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_USER_PRODUCT_REQUEST = "GET_USER_PRODUCT_REQUEST";
export const GET_USER_PRODUCT_SUCCESS = "GET_USER_PRODUCT_SUCCESS";
export const GET_USER_PRODUCT_FAIL = "GET_USER_PRODUCT_FAIL";

export const GET_CATEGORY_PRODUCT_REQUEST = "GET_CATEGORY_PRODUCT_REQUEST";
export const GET_CATEGORY_PRODUCT_SUCCESS = "GET_CATEGORY_PRODUCT_SUCCESS";
export const GET_CATEGORY_PRODUCT_FAIL = "GET_CATEGORY_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_IMAGE_REQUEST = "DELETE_PRODUCT_IMAGE_REQUEST";
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_IMAGE_SUCCESS";
export const DELETE_PRODUCT_IMAGE_FAIL = "DELETE_PRODUCT_IMAGE_FAIL";

export const UPDATE_PRODUCT_IMAGE_REQUEST = "UPDATE_PRODUCT_IMAGE_REQUEST";
export const UPDATE_PRODUCT_IMAGE_SUCCESS = "UPDATE_PRODUCT_IMAGE_SUCCESS";
export const UPDATE_PRODUCT_IMAGE_FAIL = "UPDATE_PRODUCT_IMAGE_FAIL";

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const UPDATE_PRODUCT_STATUS_REQUEST = "UPDATE_PRODUCT_STATUS_REQUEST";
export const UPDATE_PRODUCT_STATUS_SUCCESS = "UPDATE_PRODUCT_STATUS_SUCCESS";
export const UPDATE_PRODUCT_STATUS_FAIL = "UPDATE_PRODUCT_STATUS_FAIL";

export const ADD_WISHLIST_PRODUCT_REQUEST = "ADD_WISHLIST_PRODUCT_REQUEST";
export const ADD_WISHLIST_PRODUCT_SUCCESS = "ADD_WISHLIST_PRODUCT_SUCCESS";
export const ADD_WISHLIST_PRODUCT_FAIL = "ADD_WISHLIST_PRODUCT_FAIL";

export const GET_WISHLIST_PRODUCT_REQUEST = "GET_WISHLIST_PRODUCT_REQUEST";
export const GET_WISHLIST_PRODUCT_SUCCESS = "GET_WISHLIST_PRODUCT_SUCCESS";
export const GET_WISHLIST_PRODUCT_FAIL = "GET_WISHLIST_PRODUCT_FAIL";

export const DELETE_WISHLIST_PRODUCT_REQUEST =
  "DELETE_WISHLIST_PRODUCT_REQUEST";
export const DELETE_WISHLIST_PRODUCT_SUCCESS =
  "DELETE_WISHLIST_PRODUCT_SUCCESS";
export const DELETE_WISHLIST_PRODUCT_FAIL = "DELETE_WISHLIST_PRODUCT_FAIL";
