export const GET_SUB_CATEGORY_REQUEST = "GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAIL = "GET_SUB_CATEGORY_FAIL";

export const GET_ALL_SUB_CATEGORY_REQUEST = "GET_ALL_SUB_CATEGORY_REQUEST";
export const GET_ALL_SUB_CATEGORY_SUCCESS = "GET_ALL_SUB_CATEGORY_SUCCESS";
export const GET_ALL_SUB_CATEGORY_FAIL = "GET_ALL_SUB_CATEGORY_FAIL";

export const UPDATE_SUB_CATEGORY_STATUS_REQUEST =
  "UPDATE_SUB_CATEGORY_STATUS_REQUEST";
export const UPDATE_SUB_CATEGORY_STATUS_SUCCESS =
  "UPDATE_SUB_CATEGORY_STATUS_SUCCESS";
export const UPDATE_SUB_CATEGORY_STATUS_FAIL =
  "UPDATE_SUB_CATEGORY_STATUS_FAIL";

export const DELETE_SUB_CATEGORY_REQUEST = "DELETE_SUB_CATEGORY_REQUEST";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAIL = "DELETE_SUB_CATEGORY_FAIL";

export const CREATE_SUB_CATEGORY_REQUEST = "CREATE_SUB_CATEGORY_REQUEST";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_FAIL = "CREATE_SUB_CATEGORY_FAIL";

export const UPDATE_SUB_CATEGORY_REQUEST = "UPDATE_SUB_CATEGORY_REQUEST";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAIL = "UPDATE_SUB_CATEGORY_FAIL";
