export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";

export const GET_CONTACT_US_REQUEST = "GET_CONTACT_US_REQUEST";
export const GET_CONTACT_US_SUCCESS = "GET_CONTACT_US_SUCCESS";
export const GET_CONTACT_US_FAIL = "GET_CONTACT_US_FAIL";

export const HELP_REQUEST = "HELP_REQUEST";
export const HELP_SUCCESS = "HELP_SUCCESS";
export const HELP_FAIL = "HELP_FAIL";

export const GET_HELP_REQUEST = "GET_HELP_REQUEST";
export const GET_HELP_SUCCESS = "GET_HELP_SUCCESS";
export const GET_HELP_FAIL = "GET_HELP_FAIL";

export const EDIT_PROFILE_IMAGE_REQUEST = "EDIT_PROFILE_IMAGE_REQUEST";
export const EDIT_PROFILE_IMAGE_SUCCESS = "EDIT_PROFILE_IMAGE_SUCCESS";
export const EDIT_PROFILE_IMAGE_FAIL = "EDIT_PROFILE_IMAGE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const UPDATE_USER_STATUS_REQUEST = "UPDATE_USER_STATUS_REQUEST";
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS";
export const UPDATE_USER_STATUS_FAIL = "UPDATE_USER_STATUS_FAIL";
