import { all } from "redux-saga/effects";
import {
  forgotApiWatcher,
  loginApiWatcher,
  logoutApiWatcher,
  otpApiWatcher,
  registerApiWatcher,
  resendOtpWatcher,
  resetApiWatcher,
  userDataWatcher,
  AdminLoginWatcher,
} from "./AuthSaga";
import {
  GetBannerWatcher,
  GetAllBannerWatcher,
  UpdateBannerImageWatcher,
  UpdateBannerStatusWatcher,
  DeleteBannerWatcher,
} from "./BannerSaga";
import {
  GetCategoryWatcher,
  GetAllCategoryWatcher,
  UpdateCategoryStatusWatcher,
  DeleteCategoryWatcher,
  CreateCategoryWatcher,
  UpdateCategoryWatcher,
} from "./CategorySaga";
import {
  GetSubCategoryWatcher,
  GetAllSubCategoryWatcher,
  UpdateSubCategoryStatusWatcher,
  DeleteSubCategoryWatcher,
  CreateSubCategoryWatcher,
  UpdateSubCategoryWatcher,
} from "./SubCategorySaga";
import {
  NewProductWatcher,
  GetProductWatcher,
  GetUserProductWatcher,
  GetCategoryProductWatcher,
  DeleteProductWatcher,
  GetProductByIdWatcher,
  UpdateProductWatcher,
  DeleteProductImageWatcher,
  UpdateProductImageWatcher,
  GetAllProductWatcher,
  UpdateProductStatusWatcher,
  AddWishlistProductWatcher,
  GetWishlistProductWatcher,
  DeleteWishlistProductWatcher,
} from "./ProductSaga";
import {
  ContactUsWatcher,
  getContactUsWatcher,
  EditProfileImageWatcher,
  EditProfileWatcher,
  GetAllUsersWatcher,
  UpdateUserStatusWatcher,
  HelpWatcher,
  GetHelpWatcher,
} from "./UserSaga";
import {
  GetAllBrandWatcher,
  GetBrandWatcher,
  UpdateBrandStatusWatcher,
  UpdateBrandWatcher,
  CreateBrandWatcher,
  DeleteBrandWatcher,
} from "./BrandSaga";
import {
  GetAdminDashboardDataWatcher,
  GetAllHelpMessagesWatcher,
} from "./AdminSaga";

export default function* rootSaga() {
  yield all([
    registerApiWatcher(),
    otpApiWatcher(),
    loginApiWatcher(),
    forgotApiWatcher(),
    resetApiWatcher(),
    logoutApiWatcher(),
    userDataWatcher(),
    HelpWatcher(),
    GetHelpWatcher(),
    resendOtpWatcher(),
    GetBannerWatcher(),
    GetCategoryWatcher(),
    GetSubCategoryWatcher(),
    NewProductWatcher(),
    GetProductWatcher(),
    GetUserProductWatcher(),
    GetCategoryProductWatcher(),
    DeleteProductWatcher(),
    GetProductByIdWatcher(),
    UpdateProductWatcher(),
    DeleteProductImageWatcher(),
    UpdateProductImageWatcher(),
    AddWishlistProductWatcher(),
    GetWishlistProductWatcher(),
    DeleteWishlistProductWatcher(),
    ContactUsWatcher(),
    getContactUsWatcher(),
    EditProfileImageWatcher(),
    EditProfileWatcher(),
    GetAllCategoryWatcher(),
    UpdateCategoryStatusWatcher(),
    DeleteCategoryWatcher(),
    CreateCategoryWatcher(),
    UpdateCategoryWatcher(),
    GetAllSubCategoryWatcher(),
    UpdateSubCategoryStatusWatcher(),
    DeleteSubCategoryWatcher(),
    CreateSubCategoryWatcher(),
    UpdateSubCategoryWatcher(),
    GetAllUsersWatcher(),
    UpdateUserStatusWatcher(),
    GetAllProductWatcher(),
    UpdateProductStatusWatcher(),
    GetAllBrandWatcher(),
    GetBrandWatcher(),
    UpdateBrandStatusWatcher(),
    UpdateBrandWatcher(),
    CreateBrandWatcher(),
    DeleteBrandWatcher(),
    AdminLoginWatcher(),
    GetAdminDashboardDataWatcher(),
    GetAllHelpMessagesWatcher(),
    GetAllBannerWatcher(),
    UpdateBannerImageWatcher(),
    UpdateBannerStatusWatcher(),
    DeleteBannerWatcher(),
  ]);
}
